### ISSUE TITLE
Heap-buffer-overflow caused by out-of-bounds vector access when using SetScalingTechnique(FIXEDAUTO) in BGV

### ISSUE THREAD

**Issue by ailanxier** [openfheorg/openfhe-development#374]
In [simple-integers-bgvrns example](https://github.com/openfheorg/openfhe-development/blob/main/src/pke/examples/simple-integers-bgvrns.cpp), the program can run normally when `SetScalingTechnique(FIXEDAUTO)` (or `FLEXIBLEAUTO`) is used instead of the default value `FLEXIBLEAUTOEXT`. However, a heap-buffer-overflow can be detected by AddressSanitizer. By tracing the error position indicated in the ASAN report, I found that there was no strict boundary check for the `vector` in [bgvrns-parametergeneration.cpp](https://github.com/openfheorg/openfhe-development/blob/main/src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp). 
Since the `operator[]` of the `vector` does not automatically perform boundary checking, the program can run normally but will be detected by AddressSanitizer. Adding the condition `moduliQ.size() > numPrimes` before judging `moduliQ[1] == moduliQ[numPrimes]` can solve this problem. However, as long as `numPrimes` is small, I am concerned that `moduliQ[1]` and `moduliQ[0]` may also pose similar risks, and it is currently unclear whether there are any limitations on the size of `numPrimes`.
```cpp
// add one line in simple-integers-bgvrns.cpp
    parameters.SetScalingTechnique(FIXEDAUTO); // or FLEXIBLEAUTO
    
// ===========  in source code: src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp ==============
    size_t numModuli = scalTech == FLEXIBLEAUTOEXT ? numPrimes + 1 : numPrimes;
    std::vector<NativeInteger> moduliQ(numModuli);                       // defined here: src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp:181
    
// !!! moduliQ[numPrimes] may result in out-of-bounds vector access
    while (moduliQ[1] == moduliQ[0] || moduliQ[1] == moduliQ[numPrimes] || moduliQ[1] == plainModulusInt) { // crash here: src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp:253
         moduliQ[1] = NextPrime<NativeInteger>(moduliQ[1], cyclOrder);   
    }

// ================ ASAN report =====================
==378525==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6030000008f8 at pc 0x55ccf2901447 bp 0x7ffede825dd0 sp 0x7ffede825dc0
READ of size 8 at 0x6030000008f8 thread T0
    #0 0x55ccf2901446 in intnat::NativeIntegerT<unsigned long>::Compare(intnat::NativeIntegerT<unsigned long> const&) const /root/openfhe-development/src/core/include/math/hal/intnat/ubintnat.h:1800
    #1 0x55ccf2901446 in lbcrypto::operator==(intnat::NativeIntegerT<unsigned long> const&, intnat::NativeIntegerT<unsigned long> const&) /root/openfhe-development/src/core/include/math/hal/integer.h:553
    #2 0x55ccf2901446 in lbcrypto::ParameterGenerationBGVRNS::computeModuli(std::shared_ptr<lbcrypto::CryptoParametersBase<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned int> > > > >, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const /root/openfhe-development/src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp:252
    #3 0x55ccf2905929 in lbcrypto::ParameterGenerationBGVRNS::ParamsGenBGVRNS(std::shared_ptr<lbcrypto::CryptoParametersBase<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned int> > > > >, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const /root/openfhe-development/src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp:391
    #4 0x55ccf26b7705 in lbcrypto::SchemeBase<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned int> > > >::ParamsGenBGVRNS(std::shared_ptr<lbcrypto::CryptoParametersBase<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned int> > > > >, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const /root/openfhe-development/src/pke/include/schemebase/base-scheme.h:174
    #5 0x55ccf26a4473 in lbcrypto::CryptoContextBGVRNS::ContextType lbcrypto::genCryptoContextBGVRNSInternal<lbcrypto::CryptoContextBGVRNS, lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned int> > > >(lbcrypto::CCParams<lbcrypto::CryptoContextBGVRNS> const&) /root/openfhe-development/src/pke/include/scheme/bgvrns/gen-cryptocontext-bgvrns-internal.h:93
    #6 0x55ccf26822d0 in lbcrypto::CryptoContextBGVRNS::genCryptoContext(lbcrypto::CCParams<lbcrypto::CryptoContextBGVRNS> const&) /root/openfhe-development/src/pke/include/scheme/bgvrns/cryptocontext-bgvrns.h:61
    #7 0x55ccf26822d0 in lbcrypto::CryptoContextBGVRNS::ContextType lbcrypto::GenCryptoContext<lbcrypto::CryptoContextBGVRNS>(lbcrypto::CCParams<lbcrypto::CryptoContextBGVRNS> const&) /root/openfhe-development/src/pke/include/gen-cryptocontext.h:90
    #8 0x55ccf26822d0 in main /root/openfhe-development/src/pke/examples/simple-integers-bgvrns.cpp:46
    #9 0x7fa2f91c1d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
    #10 0x7fa2f91c1e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f)
    #11 0x55ccf2681ee4 in _start (/root/openfhe-development/build_static/bin/simple-integers-bgvrns+0x6bee4)

0x6030000008f8 is located 0 bytes to the right of 24-byte region [0x6030000008e0,0x6030000008f8)
allocated by thread T0 here:
    #0 0x7fa2f97a71c7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x55ccf28ff352 in __gnu_cxx::new_allocator<intnat::NativeIntegerT<unsigned long> >::allocate(unsigned long, void const*) /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/ext/new_allocator.h:127
    #2 0x55ccf28ff352 in std::allocator_traits<std::allocator<intnat::NativeIntegerT<unsigned long> > >::allocate(std::allocator<intnat::NativeIntegerT<unsigned long> >&, unsigned long) /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/alloc_traits.h:464
    #3 0x55ccf28ff352 in std::_Vector_base<intnat::NativeIntegerT<unsigned long>, std::allocator<intnat::NativeIntegerT<unsigned long> > >::_M_allocate(unsigned long) /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_vector.h:346
    #4 0x55ccf28ff352 in std::_Vector_base<intnat::NativeIntegerT<unsigned long>, std::allocator<intnat::NativeIntegerT<unsigned long> > >::_M_create_storage(unsigned long) /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_vector.h:361
    #5 0x55ccf28ff352 in std::_Vector_base<intnat::NativeIntegerT<unsigned long>, std::allocator<intnat::NativeIntegerT<unsigned long> > >::_Vector_base(unsigned long, std::allocator<intnat::NativeIntegerT<unsigned long> > const&) /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_vector.h:305
    #6 0x55ccf28ff352 in std::vector<intnat::NativeIntegerT<unsigned long>, std::allocator<intnat::NativeIntegerT<unsigned long> > >::vector(unsigned long, std::allocator<intnat::NativeIntegerT<unsigned long> > const&) /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_vector.h:511
    #7 0x55ccf28ff352 in lbcrypto::ParameterGenerationBGVRNS::computeModuli(std::shared_ptr<lbcrypto::CryptoParametersBase<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned int> > > > >, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const /root/openfhe-development/src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp:180
    #8 0x55ccf2905929 in lbcrypto::ParameterGenerationBGVRNS::ParamsGenBGVRNS(std::shared_ptr<lbcrypto::CryptoParametersBase<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned int> > > > >, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const /root/openfhe-development/src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp:391
    #9 0x55ccf26b7705 in lbcrypto::SchemeBase<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned int> > > >::ParamsGenBGVRNS(std::shared_ptr<lbcrypto::CryptoParametersBase<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned int> > > > >, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) const /root/openfhe-development/src/pke/include/schemebase/base-scheme.h:174
    #10 0x55ccf26a4473 in lbcrypto::CryptoContextBGVRNS::ContextType lbcrypto::genCryptoContextBGVRNSInternal<lbcrypto::CryptoContextBGVRNS, lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned int> > > >(lbcrypto::CCParams<lbcrypto::CryptoContextBGVRNS> const&) /root/openfhe-development/src/pke/include/scheme/bgvrns/gen-cryptocontext-bgvrns-internal.h:93
    #11 0x55ccf26822d0 in lbcrypto::CryptoContextBGVRNS::genCryptoContext(lbcrypto::CCParams<lbcrypto::CryptoContextBGVRNS> const&) /root/openfhe-development/src/pke/include/scheme/bgvrns/cryptocontext-bgvrns.h:61
    #12 0x55ccf26822d0 in lbcrypto::CryptoContextBGVRNS::ContextType lbcrypto::GenCryptoContext<lbcrypto::CryptoContextBGVRNS>(lbcrypto::CCParams<lbcrypto::CryptoContextBGVRNS> const&) /root/openfhe-development/src/pke/include/gen-cryptocontext.h:90
    #13 0x55ccf26822d0 in main /root/openfhe-development/src/pke/examples/simple-integers-bgvrns.cpp:46
    #14 0x7fa2f91c1d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
```
PS: The issues I reported can be easily reproduced in the examples provided by OpenFHE. I would appreciate it if these issues could be confirmed as soon as possible, so that I can mention them in my research. Thanks in advance.

**Comment by dsuponitskiy** [comment]
A fix is currently available in the dev branch of OpenFHE. We will move it to main with the next OpenFHE release.
