### ISSUE TITLE
Stack-use-after-scope error in simple-integers-serial example

### ISSUE THREAD

**Issue by Maokami** [openfheorg/openfhe-development#528]
Hi everyone!

I found that when I compiled [simple-integers-serial](https://github.com/openfheorg/openfhe-development/blob/dev/src/pke/examples/simple-integers-serial.cpp) example with address sanitizer and ran it, stack-use-after-scope could be detected.
```shell
==50232==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ff7b52f7f80 at pc 0x00010c175e5c bp 0x7ff7b52f76b0 sp 0x7ff7b52f76a8
READ of size 8 at 0x7ff7b52f7f80 thread T0
    #0 0x10c175e5b in lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned long long>>>::DCRTPolyImpl(std::__1::shared_ptr<lbcrypto::ILDCRTParams<bigintdyn::ubint<unsigned long long>>> const&, Format, bool)+0x3cb (libOPENFHEcore.1.1.0.dylib:x86_64+0x127e5b) (BuildId: d2bccfe6ea783c94964f214eba40a0bf32000000200000000100000000000d00)
    #1 0x10c0a03bd in lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned long long>>>::FastExpandCRTBasisPloverQ(lbcrypto::DCRTPolyInterface<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned long long>>>, bigintdyn::mubintvec<bigintdyn::ubint<unsigned long long>>, intnat::NativeVectorT<intnat::NativeIntegerT<unsigned long long>>, lbcrypto::PolyImpl>::CRTBasisExtensionPrecomputations const&)+0x21d (libOPENFHEcore.1.1.0.dylib:x86_64+0x523bd) (BuildId: d2bccfe6ea783c94964f214eba40a0bf32000000200000000100000000000d00)
    #2 0x10bad7186 in lbcrypto::LeveledSHEBFVRNS::EvalMult(std::__1::shared_ptr<lbcrypto::CiphertextImpl<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned long long>>>> const>, std::__1::shared_ptr<lbcrypto::CiphertextImpl<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned long long>>>> const>) const+0x42a6 (libOPENFHEpke.1.1.0.dylib:x86_64+0x239186) (BuildId: b463f8c82b4a3f0d9f105bee89d4cd3532000000200000000100000000000d00)
    #3 0x10bae7234 in lbcrypto::LeveledSHEBFVRNS::EvalMult(std::__1::shared_ptr<lbcrypto::CiphertextImpl<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned long long>>>> const>, std::__1::shared_ptr<lbcrypto::CiphertextImpl<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned long long>>>> const>, std::__1::shared_ptr<lbcrypto::EvalKeyImpl<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned long long>>>>>) const+0x234 (libOPENFHEpke.1.1.0.dylib:x86_64+0x249234) (BuildId: b463f8c82b4a3f0d9f105bee89d4cd3532000000200000000100000000000d00)
    #4 0x10bd876ef in lbcrypto::SchemeBase<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned long long>>>>::EvalMult(std::__1::shared_ptr<lbcrypto::CiphertextImpl<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned long long>>>> const>, std::__1::shared_ptr<lbcrypto::CiphertextImpl<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned long long>>>> const>, std::__1::shared_ptr<lbcrypto::EvalKeyImpl<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned long long>>>>>) const+0x47f (libOPENFHEpke.1.1.0.dylib:x86_64+0x4e96ef) (BuildId: b463f8c82b4a3f0d9f105bee89d4cd3532000000200000000100000000000d00)
    #5 0x10ad22861 in lbcrypto::CryptoContextImpl<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned long long>>>>::EvalMult(std::__1::shared_ptr<lbcrypto::CiphertextImpl<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned long long>>>> const>, std::__1::shared_ptr<lbcrypto::CiphertextImpl<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned long long>>>> const>) const+0x8c1 (simple-integers-serial:x86_64+0x10011e861) (BuildId: 294d719ee26f30e1ae7c3e1e6eb4f31632000000200000000100000000000d00)
    #6 0x10ad18057 in main+0x4c57 (simple-integers-serial:x86_64+0x100114057) (BuildId: 294d719ee26f30e1ae7c3e1e6eb4f31632000000200000000100000000000d00)
    #7 0x7ff80fe7541e in start+0x76e (dyld:x86_64+0xfffffffffff6e41e) (BuildId: 9e98a840a3ac31c1ab97829af9bd686432000000200000000100000000040d00)

Address 0x7ff7b52f7f80 is located in stack of thread T0 at offset 1312 in frame
    #0 0x10bad2eef in lbcrypto::LeveledSHEBFVRNS::EvalMult(std::__1::shared_ptr<lbcrypto::CiphertextImpl<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned long long>>>> const>, std::__1::shared_ptr<lbcrypto::CiphertextImpl<lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned long long>>>> const>) const+0xf (libOPENFHEpke.1.1.0.dylib:x86_64+0x234eef) (BuildId: b463f8c82b4a3f0d9f105bee89d4cd3532000000200000000100000000000d00)

  This frame has 43 object(s):
    [32, 48) 'ref.tmp'
    [64, 80) 'ref.tmp2'
    [96, 120) 'errMsg'
    [160, 184) 'ref.tmp5'
    [224, 240) 'cryptoParams'
    [256, 280) 'cv1'
    [320, 344) 'cv2'
    [384, 408) 'cvMult'
    [448, 464) 'ref.tmp50'
    [480, 496) 'ref.tmp54'
    [512, 528) 'ref.tmp89'
    [544, 560) 'ref.tmp93'
    [576, 592) 'ref.tmp136'
    [608, 624) 'ref.tmp142'
    [640, 760) 'basisPQ'
    [800, 816) 'ref.tmp190'
    [832, 848) 'ref.tmp196'
    [864, 880) 'ref.tmp202'
    [896, 912) 'agg.tmp'
    [928, 984) 'ref.tmp325'
    [1024, 1040) 'ref.tmp327'
    [1056, 1072) 'ref.tmp352'
    [1088, 1104) 'ref.tmp357'
    [1120, 1240) 'basisPQ394'
    [1280, 1296) 'ref.tmp395'
    [1312, 1328) 'ref.tmp400' <== Memory access at offset 1312 is inside this variable
    [1344, 1360) 'ref.tmp405'
    [1376, 1392) 'ref.tmp484'
    [1408, 1424) 'ref.tmp541'
    [1440, 1464) 'isFirstAdd'
    [1504, 1560) 'ref.tmp618'
    [1600, 1656) 'ref.tmp635'
    [1696, 1752) 'ref.tmp670'
    [1792, 1808) 'ref.tmp672'
    [1824, 1880) 'ref.tmp692'
    [1920, 1936) 'ref.tmp694'
    [1952, 2008) 'ref.tmp743'
    [2048, 2064) 'ref.tmp745'
    [2080, 2136) 'ref.tmp785'
    [2176, 2192) 'ref.tmp787'
    [2208, 2224) 'ref.tmp814'
    [2240, 2248) 'ref.tmp839'
    [2272, 2288) 'ref.tmp884'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-use-after-scope (libOPENFHEcore.1.1.0.dylib:x86_64+0x127e5b) (BuildId: d2bccfe6ea783c94964f214eba40a0bf32000000200000000100000000000d00) in lbcrypto::DCRTPolyImpl<bigintdyn::mubintvec<bigintdyn::ubint<unsigned long long>>>::DCRTPolyImpl(std::__1::shared_ptr<lbcrypto::ILDCRTParams<bigintdyn::ubint<unsigned long long>>> const&, Format, bool)+0x3cb
Shadow bytes around the buggy address:
  0x1ffef6a5efa0: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f2 f2 f2 f2 f2
  0x1ffef6a5efb0: f8 f8 f2 f2 f8 f8 f2 f2 f8 f8 f2 f2 00 00 f2 f2
  0x1ffef6a5efc0: f8 f8 f8 f8 f8 f8 f8 f2 f2 f2 f2 f2 f8 f8 f2 f2
  0x1ffef6a5efd0: f8 f8 f2 f2 f8 f8 f2 f2 00 00 00 00 00 00 00 00
  0x1ffef6a5efe0: 00 00 00 00 00 00 00 f2 f2 f2 f2 f2 f8 f8 f2 f2
=>0x1ffef6a5eff0:[f8]f8 f2 f2 f8 f8 f2 f2 f8 f8 f2 f2 f8 f8 f2 f2
  0x1ffef6a5f000: f8 f8 f8 f2 f2 f2 f2 f2 f8 f8 f8 f8 f8 f8 f8 f2
  0x1ffef6a5f010: f2 f2 f2 f2 f8 f8 f8 f8 f8 f8 f8 f2 f2 f2 f2 f2
  0x1ffef6a5f020: f8 f8 f8 f8 f8 f8 f8 f2 f2 f2 f2 f2 f8 f8 f2 f2
  0x1ffef6a5f030: f8 f8 f8 f8 f8 f8 f8 f2 f2 f2 f2 f2 f8 f8 f2 f2
  0x1ffef6a5f040: f8 f8 f8 f8 f8 f8 f8 f2 f2 f2 f2 f2 f8 f8 f2 f2
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==50232==ABORTING
```
The error is due to the use of [EvalMut](https://github.com/openfheorg/openfhe-development/blob/7d6099a9e1809ad374f9e9e4dad866cab3f418fa/src/pke/examples/simple-integers-serial.cpp#L261) in deserialized context, but I'm not sure what is the root cause of this.

**Comment by Maokami** [comment]
The following examples in pke/ produce the same error:

- depth-bfvrns
- inner-product
- simple-integers
- threshold-fhe
- threshold-fhe-5p

I guess this happens when using EvalMult in BFV scheme.

**Comment by dsuponitskiy** [comment]
A fix is currently available in the dev branch of OpenFHE. We will move it to main with the next OpenFHE release.
